name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: 782042369/nginx-file  # 替换为你的镜像名称

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # 启用 QEMU 仿真（支持跨平台构建）
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # 配置 Buildx 支持多平台
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: network=host  # 优化网络性能

      # 登录 Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERUSERNAME }}
          password: ${{ secrets.DOCKERPASSWORD }}

      # 构建并推送多平台镜像
      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64  # 指定目标平台
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
          cache-from: type=gha  # 使用 GitHub Actions 缓存
          cache-to: type=gha,mode=max
