name: CI/CD Pipeline

on:
  push:
    branches: [main]

env:
  IMAGE_NAME: your-image

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    outputs:
      dist-hash: ${{ steps.hash.outputs.value }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Frontend
        run: |
          docker build -t frontend-builder --target builder .
          docker cp $(docker create frontend-builder):/app/dist ./dist

      - name: Generate Dist Hash
        id: hash
        run: echo "value=$(sha256sum dist/* | sha256sum | cut -d' ' -f1)" >> $GITHUB_OUTPUT

      - name: Upload Dist
        uses: actions/upload-artifact@v3
        with:
          name: frontend-dist
          path: dist

  build-nginx:
    needs: build-frontend
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]
    steps:
      - name: Download Dist
        uses: actions/download-artifact@v3
        with:
          name: frontend-dist

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.nginx
          platforms: ${{ matrix.platform }}
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest
